/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.farecardsystem.config.TravelConfig;
import org.farecardsystem.entity.*;
import org.farecardsystem.payment.CashPaymentStrategy;
import org.farecardsystem.payment.Payment;
import org.farecardsystem.util.TravelFare;
import org.junit.Before;
import org.junit.Test;

import java.util.Arrays;

public class FareCardSystemTest {

	private TravelFare travelFare = new TravelFare();
	private TravelConfig travelConfig = new TravelConfig();

	@Before
	public void setup() {
		// Setting up the fare details and zones details for starting and ending stations in travel config

		// When travelling from zone1 to zone1 and the travel fare would be 2.5
		TravelRegulation travelRegulation1 = new TravelRegulation();
		travelRegulation1.setTravelFare(2.5);
		TravelPoint travelPoint = new TravelPoint();
		travelPoint.setStartingPointTravelZone(Zone.ZONE1);
		travelPoint.setEndingPointTravelZone(Zone.ZONE1);
		travelRegulation1.addTravelPoints(travelPoint);
		travelRegulation1.setModeOfTransportation(ModeOfTransportation.TRAIN);
		travelConfig.addTravelRegulation(travelRegulation1);

		// When travelling from zone2 to zone2 or zone3 to zone3 and the travel fare would be 2.0
		TravelRegulation travelRegulation2 = new TravelRegulation();
		travelRegulation2.setTravelFare(2.0);
		TravelPoint travelPoint1 = new TravelPoint();
		travelPoint1.setStartingPointTravelZone(Zone.ZONE2);
		travelPoint1.setEndingPointTravelZone(Zone.ZONE2);
		travelRegulation2.addTravelPoints(travelPoint1);
		TravelPoint travelPoint2 = new TravelPoint();
		travelPoint2.setStartingPointTravelZone(Zone.ZONE3);
		travelPoint2.setEndingPointTravelZone(Zone.ZONE3);
		travelRegulation2.addTravelPoints(travelPoint2);
		travelRegulation2.setModeOfTransportation(ModeOfTransportation.TRAIN);
		travelConfig.addTravelRegulation(travelRegulation2);

		// When travelling from zone1 to zone2 or zone2 to zone1 or zone1 to zone3 or zone3 to zone1 and the travel fare would be 3.0
		TravelRegulation travelRegulation3 = new TravelRegulation();
		travelRegulation3.setTravelFare(3.0);
		TravelPoint travelPoint3 = new TravelPoint();
		travelPoint3.setStartingPointTravelZone(Zone.ZONE1);
		travelPoint3.setEndingPointTravelZone(Zone.ZONE2);
		travelRegulation3.addTravelPoints(travelPoint3);
		TravelPoint travelPoint4 = new TravelPoint();
		travelPoint4.setStartingPointTravelZone(Zone.ZONE2);
		travelPoint4.setEndingPointTravelZone(Zone.ZONE1);
		travelRegulation3.addTravelPoints(travelPoint4);
		TravelPoint travelPoint5 = new TravelPoint();
		travelPoint5.setStartingPointTravelZone(Zone.ZONE1);
		travelPoint5.setEndingPointTravelZone(Zone.ZONE3);
		travelRegulation3.addTravelPoints(travelPoint5);
		TravelPoint travelPoint6 = new TravelPoint();
		travelPoint6.setStartingPointTravelZone(Zone.ZONE3);
		travelPoint6.setEndingPointTravelZone(Zone.ZONE1);
		travelRegulation3.addTravelPoints(travelPoint6);
		travelRegulation3.setModeOfTransportation(ModeOfTransportation.TRAIN);
		travelConfig.addTravelRegulation(travelRegulation3);

		// When travelling from zone2 to zone3 or zone3 to zone2 and the travel fare would be 2.25
		TravelRegulation travelRegulation4 = new TravelRegulation();
		travelRegulation4.setTravelFare(2.25);
		TravelPoint travelPoint7 = new TravelPoint();
		travelPoint7.setStartingPointTravelZone(Zone.ZONE2);
		travelPoint7.setEndingPointTravelZone(Zone.ZONE3);
		travelRegulation4.addTravelPoints(travelPoint7);
		TravelPoint travelPoint8 = new TravelPoint();
		travelPoint8.setStartingPointTravelZone(Zone.ZONE3);
		travelPoint8.setEndingPointTravelZone(Zone.ZONE2);
		travelRegulation4.addTravelPoints(travelPoint8);
		travelRegulation4.setModeOfTransportation(ModeOfTransportation.TRAIN);
		travelConfig.addTravelRegulation(travelRegulation4);

		// Setting up max allowed fare would be 3.2
		TravelRegulation travelRegulation5 = new TravelRegulation();
		travelRegulation5.setTravelFare(3.2);
		travelRegulation5.setModeOfTransportation(ModeOfTransportation.TRAIN);
		travelConfig.addTravelRegulation(travelRegulation5);
		travelConfig.setMaxAllowedFareForTravel(3.2);

		// Setting up the mode of transportation would be BUS and the travel fare would be 1.8 with all zones
		TravelRegulation travelRegulation6 = new TravelRegulation();
		travelRegulation6.setModeOfTransportation(ModeOfTransportation.BUS);
		travelRegulation6.setTravelFare(1.8);
		travelConfig.addTravelRegulation(travelRegulation6);
		travelFare.setTravelConfig(travelConfig);
	}

	@Test
	public void testTravel() {
		CardEventListener cardEventListener = new CardEventListener(travelFare);
		CashPaymentStrategy cashPaymentStrategy = new CashPaymentStrategy();
		Payment payment = new Payment(ModeOfPayment.CASH);
		Card card = new Card();
		card.addPropertyChangeListener(cardEventListener);

		card.loadBalance(30, payment);
		card.checkInCheckOut(ModeOfTransportation.TRAIN, new Station("Holborn", Arrays.asList(Zone.ZONE1)));
		System.out.println("ModeOfTransportation: TRAIN, StartingPointStation: Holborn, Zone: Zone1, Card Balance -> " + card.getBalance());
		card.checkInCheckOut(ModeOfTransportation.TRAIN, new Station("Earl's Court", Arrays.asList(Zone.ZONE1, Zone.ZONE2)));
		System.out.println("ModeOfTransportation: TRAIN, EndingPointStation: Earl's Court, Zone: (Zone1, Zone2), Card Balance -> " + card.getBalance());

		card.checkInCheckOut(ModeOfTransportation.BUS, new Station("Earl's Court", Arrays.asList(Zone.ZONE1, Zone.ZONE2)));
		System.out.println("ModeOfTransportation: 328 BUS, StartingPointStation: Earl's Court, Zone: (Zone1, ZONE2), Card Balance -> " + card.getBalance());
		card.checkInCheckOut(ModeOfTransportation.BUS, new Station("Chelsea", Arrays.asList()));
		System.out.println("ModeOfTransportation: 328 BUS, EndingPointStation: Chelsea, Zone: No Zone, Card Balance -> " + card.getBalance());

		card.checkInCheckOut(ModeOfTransportation.TRAIN, new Station("Earl's Court", Arrays.asList(Zone.ZONE1, Zone.ZONE2)));
		System.out.println("ModeOfTransportation: TRAIN, StartingPointStation: Earl's Court, Zone: (Zone1, ZONE2), Card Balance -> " + card.getBalance());
		card.checkInCheckOut(ModeOfTransportation.TRAIN, new Station("HammerSmith", Arrays.asList(Zone.ZONE2)));
		System.out.println("ModeOfTransportation: TRAIN, EndingPointStation: HammerSmith, Zone: Zone2, Card Balance -> " + card.getBalance());
	}

}
